const KEY='bz_demo_v2';
let D;try{D=JSON.parse(localStorage.getItem(KEY))}catch(e){}if(!D)D=structuredClone(SEED);
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(D))}catch(e){}};
let session=null,tab='overview',F={dest:'',days:'',budget:'',sort:''};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inr=n=>'₹'+Number(n).toLocaleString('en-IN');
const fd=d=>new Date(d+'T00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
const wa=t=>`https://wa.me/${D.settings.wa}?text=${encodeURIComponent(t)}`;
const waBtn=(t,l='Enquire on WhatsApp',c='btn wa sm')=>`<a class="${c}" target="_blank" rel="noopener" href="${wa(t)}">${l}</a>`;
const live=()=>D.tours.filter(t=>t.status==='live');
const dayN=t=>t.itinerary.length;
const stars=n=>`<span class="stars" aria-label="${n} stars">${'★'.repeat(n)}${'☆'.repeat(5-n)}</span>`;
function art(h,label,scene){const k='g'+Math.random().toString(36).slice(2,7);
 const front=scene%2?'<path d="M0 200v-35l60-10 40 20 70-30 90 25 60-20 80 20v30z" fill="hsl('+h+',40%,28%)"/><path d="M150 120h100v40H150z M140 120l60-30 60 30z" fill="hsl('+h+',55%,70%)"/>':'<path d="M0 200V120l70-55 60 50 70-80 80 90 50-35 70 60v50z" fill="hsl('+h+',35%,45%)"/><path d="M0 200v-40l90-30 80 40 90-45 140 50v25z" fill="hsl('+h+',40%,30%)"/>';
 return `<div class="ph"><svg viewBox="0 0 400 200" preserveAspectRatio="xMidYMid slice" role="img" aria-label="${esc(label)}"><defs><linearGradient id="${k}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="hsl(${h},60%,76%)"/><stop offset="1" stop-color="hsl(${h},50%,93%)"/></linearGradient></defs><rect width="400" height="200" fill="url(#${k})"/><circle cx="310" cy="48" r="22" fill="hsl(${h},85%,90%)"/>${front}</svg><span class="tag">Photo slot: ${esc(label)}</span></div>`}
const tourCard=t=>`<a class="card" href="#/tour/${esc(t.slug)}" style="text-decoration:none;color:inherit"><div class="img">${art(t.hue,t.photo,t.id)}</div><div class="body"><h3>${esc(t.name)}</h3><div class="muted">${dayN(t)} days · ${esc(t.route)}</div><div class="chips">${t.highlights.map(h=>`<span>${esc(h)}</span>`).join('')}</div><div class="price">from ${inr(t.price)} <span class="muted">per person</span></div></div></a>`;
const reviews=()=>`<div class="grid">${D.reviews.map(r=>`<div class="card body">${stars(r.rating)}<p>“${esc(r.text)}”</p><div class="muted"><b>${esc(r.name)}</b> · ${esc(r.trip)}</div></div>`).join('')}</div>`;
const faqHtml=(n=99)=>FAQ.slice(0,n).map(([q,a])=>`<details><summary>${esc(q)}</summary><p class="muted">${esc(a)}</p></details>`).join('');
function deps(n=6){const r=[];live().forEach(t=>t.dates.forEach(d=>r.push([d,t])));r.sort((a,b)=>a[0]<b[0]?-1:1);return r.length?`<div class="tablewrap"><table><tr><th>Date</th><th>Tour</th><th>Days</th><th>Price</th><th></th></tr>${r.slice(0,n).map(([d,t])=>`<tr><td>${fd(d)}</td><td><a href="#/tour/${t.slug}">${esc(t.name)}</a></td><td>${dayN(t)}</td><td>${inr(t.price)}</td><td>${waBtn('Enquiry: '+t.name+' departing '+fd(d),'Book')}</td></tr>`).join('')}</table></div>`:'<p class="muted">Dates on request.</p>'}
const cta=()=>`<section class="sec wrap"><div class="cta"><h2>Ready for Bhutan?</h2><p>Tell us your dates and we will design the trip with you.</p><a class="btn" style="background:#fff;color:var(--maroon)" href="#/plan">Plan my trip</a> ${waBtn('Hi, I want to plan a Bhutan trip.','Chat on WhatsApp','btn wa')}</div></section>`;
const crumbs=a=>`<div class="crumbs"><a href="#/">Home</a>${a.map(([l,h])=>' / '+(h?`<a href="${h}">${esc(l)}</a>`:esc(l))).join('')}</div>`;
function setMeta(t,d,ld){document.title=t;let m=$('meta[name=description]');m.content=d||'';$('#ld').textContent=ld?JSON.stringify(ld):''}
const seo=k=>D.seo[k]||{t:'La Bhutanz Tours',d:''};
const filtered=()=>{let a=live().filter(t=>(!F.dest||t.route.includes(F.dest))&&(!F.days||(F.days==='s'?dayN(t)<=6:F.days==='m'?dayN(t)>=7&&dayN(t)<=8:dayN(t)>=9))&&(!F.budget||(F.budget==='l'?t.price<40000:F.budget==='m'?t.price>=40000&&t.price<70000:t.price>=70000)));if(F.sort==='lo')a.sort((x,y)=>x.price-y.price);if(F.sort==='hi')a.sort((x,y)=>y.price-x.price);return a};
const sel=(n,l,o)=>`<div><label>${l}</label><select data-f="${n}">${o.map(([v,t])=>`<option value="${v}" ${F[n]===v?'selected':''}>${t}</option>`).join('')}</select></div>`;
const destOpt=[['','Any destination'],...DEST.map(d=>[d.name,d.name])];

const pages={
home(){const s=seo('home');setMeta(s.t,s.d,{'@context':'https://schema.org','@type':'TravelAgency',name:'La Bhutanz Tours',url:'https://www.bhutanz.com/',areaServed:'IN',address:{'@type':'PostalAddress',addressLocality:'Mumbai',addressCountry:'IN'}});
return `<section class="hero" style="--heroimg:linear-gradient(135deg,#4a1b12,#b88a2e)"><div class="wrap"><h1>Bhutan, planned around you</h1><p>Private guides, permits and handpicked stays. Real conversations, not cookie-cutter packages.</p>
<form class="searchbar" id="hs">${sel('dest','Destination',destOpt)}${sel('days','Duration',[['','Any'],['s','Up to 6 days'],['m','7 to 8 days'],['l','9+ days']])}${sel('budget','Budget',[['','Any'],['l','Under ₹40k'],['m','₹40k to ₹70k'],['h','₹70k+']])}<div><label>&nbsp;</label><button class="btn" style="width:100%">Find trips</button></div></form></div></section>
<div class="stripe"><div class="wrap"><div><b>500+</b>Travellers (sample)</div><div><b>5</b>Regions covered</div><div><b>4.8</b>Avg rating (sample)</div><div><b>24/7</b>WhatsApp support</div></div></div>
<section class="sec wrap"><h2>Popular journeys</h2><div class="grid">${live().slice(0,3).map(tourCard).join('')}</div><p><a href="#/tours">See all tours →</a></p></section>
<section class="sec wrap"><h2>Where in Bhutan?</h2><div class="grid">${DEST.map(d=>`<a class="card" href="#/destination/${d.slug}" style="text-decoration:none;color:inherit"><div class="img">${art(d.hue,d.photo,d.name.length)}</div><div class="body"><h3>${d.name}</h3><p class="muted">${esc(d.known.join(' · '))}</p></div></a>`).join('')}</div></section>
<section class="sec wrap"><h2>How it works</h2><div class="grid steps">${[['Tell us your dream','Share dates, pace and interests on WhatsApp.'],['We design your trip','Itinerary, hotels, guide and permits, with transparent INR pricing.'],['Travel stress-free','We stay on call from airport pickup to farewell.']].map(([a,b])=>`<div class="card body"><h3>${a}</h3><p class="muted">${b}</p></div>`).join('')}</div></section>
<section class="sec wrap"><h2>Upcoming departures</h2>${deps()}</section>
<section class="sec wrap"><h2>Traveller stories</h2>${reviews()}</section>
<section class="sec wrap"><h2>From the blog</h2><div class="grid">${D.posts.filter(p=>p.status==='live').slice(0,3).map(postCard).join('')}</div></section>
<section class="sec wrap"><h2>Quick answers</h2>${faqHtml(4)}<a href="#/faq">More FAQs →</a></section>${cta()}`},
tours(){const s=seo('tours');setMeta(s.t,s.d);const a=filtered();
return `<section class="sec wrap">${crumbs([['Tours']])}<h1>Bhutan tour packages</h1><p class="muted">Per-person prices in INR. Managed from the admin panel.</p><div class="filters">${sel('dest','Destination',destOpt)}${sel('days','Duration',[['','Any'],['s','Up to 6 days'],['m','7 to 8 days'],['l','9+ days']])}${sel('budget','Budget',[['','Any'],['l','Under ₹40k'],['m','₹40k to ₹70k'],['h','₹70k+']])}${sel('sort','Sort',[['','Recommended'],['lo','Price: low to high'],['hi','Price: high to low']])}<div><label>&nbsp;</label><button class="btn alt" data-clear style="width:100%">Clear filters</button></div></div>
${a.length?`<div class="grid">${a.map(tourCard).join('')}</div>`:'<p>No tours match. <a href="#/plan">Ask us for a custom trip.</a></p>'}</section>${cta()}`},
destinations(){const s=seo('destinations');setMeta(s.t,s.d);return `<section class="sec wrap">${crumbs([['Destinations']])}<h1>Bhutan destinations</h1><div class="grid">${DEST.map(d=>`<a class="card" href="#/destination/${d.slug}" style="text-decoration:none;color:inherit"><div class="img">${art(d.hue,d.photo,d.name.length)}</div><div class="body"><h3>${d.name}</h3><p class="muted">${esc(d.blurb)}</p></div></a>`).join('')}</div></section>${cta()}`},
flights(){const s=seo('flights');setMeta(s.t,s.d);return `<section class="sec wrap">${crumbs([['Flights']])}<h1>Flights to Paro</h1><p class="muted">Sample schedule and fares. Managed by the owner in the admin panel. Fares change, confirm on WhatsApp.</p><div class="tablewrap"><table><tr><th>Route</th><th>Airline</th><th>Flight</th><th>Dep</th><th>Arr</th><th>Days</th><th>Fare</th><th>Seats</th><th></th></tr>${D.flights.map(f=>`<tr><td>${esc(f.route)}</td><td>${esc(f.airline)}</td><td>${esc(f.no)}</td><td>${esc(f.dep)}</td><td>${esc(f.arr)}</td><td>${esc(f.days)}</td><td>${inr(f.price)}</td><td>${f.seats>5?'Available':f.seats+' left'}</td><td>${waBtn('Enquiry: flight '+f.no+' '+f.route,'Enquire')}</td></tr>`).join('')}</table></div></section>${cta()}`},
blog(){const s=seo('blog');setMeta(s.t,s.d);return `<section class="sec wrap">${crumbs([['Blog']])}<h1>Bhutan travel blog</h1><div class="grid">${D.posts.filter(p=>p.status==='live').map(postCard).join('')}</div></section>`},
faq(){const s=seo('faq');setMeta(s.t,s.d,{'@context':'https://schema.org','@type':'FAQPage',mainEntity:FAQ.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))});return `<section class="sec wrap">${crumbs([['FAQ']])}<h1>Frequently asked questions</h1>${faqHtml()}</section>${cta()}`},
about(){const s=seo('about');setMeta(s.t,s.d);return `<section class="sec wrap prose">${crumbs([['About']])}<h1>About La Bhutanz Tours</h1><p>We are a Mumbai-based agency that focuses only on Bhutan, designing journeys for Indian and international travellers with licensed local partners and guides. (Sample copy, replace with the client’s story.)</p><h2>What we believe</h2><p>Fewer crowds, slower days and conversations with real people. Every itinerary starts with a chat, not a template.</p><h2>Contact</h2><p>${esc(D.settings.address)}<br>${esc(D.settings.phone)} · ${esc(D.settings.email)}</p></section>${cta()}`},
plan(){const s=seo('plan');setMeta(s.t,s.d);return `<section class="sec wrap">${crumbs([['Plan my trip']])}<h1>Plan your Bhutan trip</h1><p class="muted">Fill this in. It opens WhatsApp with everything prefilled and saves it to the admin Enquiries tab (demo).</p><div class="card body" style="max-width:640px"><form id="enq"><div class="two"><div><label>Name</label><input name="n" required></div><div><label>Travellers</label><input name="p" type="number" min="1" value="2"></div><div><label>Preferred month</label><input name="m" placeholder="e.g. December"></div><div><label>Budget per person</label><select name="b"><option>Under ₹40k</option><option>₹40k to ₹70k</option><option>₹70k+</option></select></div></div><label>Tour or interest</label><select name="t"><option>Custom trip</option>${live().map(t=>`<option>${esc(t.name)}</option>`).join('')}</select><label>Notes</label><textarea name="x" placeholder="Festivals, trekking, family, honeymoon…"></textarea><p><button class="btn wa">Send on WhatsApp</button></p></form></div></section>`},
notfound(){setMeta('Page not found | La Bhutanz','');return `<section class="sec wrap"><h1>Page not found</h1><a href="#/">Go home</a></section>`}
};
const postCard=p=>`<a class="card" href="#/post/${esc(p.slug)}" style="text-decoration:none;color:inherit"><div class="img">${art(30+p.id*60,p.title,p.id)}</div><div class="body"><h3>${esc(p.title)}</h3><p class="muted">${esc(p.excerpt)}</p></div></a>`;
function post(slug){const p=D.posts.find(x=>x.slug===slug&&x.status==='live');if(!p)return pages.notfound();setMeta(p.title+' | La Bhutanz',p.excerpt,{'@context':'https://schema.org','@type':'BlogPosting',headline:p.title,description:p.excerpt});return `<section class="sec wrap prose">${crumbs([['Blog','#/blog'],[p.title]])}<h1>${esc(p.title)}</h1><p>${esc(p.body)}</p>${waBtn('Hi, I read "'+p.title+'" and want help planning.','Ask us on WhatsApp','btn wa')}</section>`}
function destPage(slug){const d=DEST.find(x=>x.slug===slug);if(!d)return pages.notfound();setMeta(d.name+', Bhutan: Guide and Tours | La Bhutanz',d.blurb);const ts=live().filter(t=>t.route.includes(d.name));return `<section class="sec wrap">${crumbs([['Destinations','#/destinations'],[d.name]])}<div class="two"><div class="card">${art(d.hue,d.photo,d.name.length)}</div><div><h1>${d.name}</h1><p>${esc(d.blurb)}</p><p><b>Best time:</b> ${d.best}</p><div class="chips">${d.known.map(k=>`<span>${esc(k)}</span>`).join('')}</div></div></div><h2 style="margin-top:32px">Tours via ${d.name}</h2><div class="grid">${ts.map(tourCard).join('')||'<p class="muted">Custom trips available.</p>'}</div></section>${cta()}`}
function tourPage(slug){const t=D.tours.find(x=>x.slug===slug&&x.status==='live');if(!t)return pages.notfound();
 setMeta(t.seoTitle||t.name+' | La Bhutanz',t.seoDesc||t.highlights.join(', '),{'@context':'https://schema.org','@type':'TouristTrip',name:t.name,description:t.seoDesc,touristType:'Leisure',offers:{'@type':'Offer',price:t.price,priceCurrency:'INR',availability:'https://schema.org/InStock'},provider:{'@type':'TravelAgency',name:'La Bhutanz Tours'}});
 const rel=live().filter(x=>x.id!==t.id).slice(0,3);
 return `<section class="sec wrap">${crumbs([['Tours','#/tours'],[t.name]])}<div class="two"><div class="card">${art(t.hue,t.photo,t.id)}</div><div><h1>${esc(t.name)}</h1><p class="muted">${dayN(t)} days · ${esc(t.route)}</p><div class="price">${inr(t.price)} <span class="muted">per person</span></div><div class="chips">${t.highlights.map(h=>`<span>${esc(h)}</span>`).join('')}</div></div></div>
<div class="two" style="margin-top:28px;align-items:start"><div><h2>Day by day</h2>${t.itinerary.map((l,i)=>{const[a,...b]=l.split(':');return `<div class="day"><b class="n">Day ${i+1}</b><div><b>${esc(a)}</b><br><span class="muted">${esc(b.join(':').trim())}</span></div></div>`}).join('')}<h2 style="margin-top:28px">Included</h2><ul>${t.inclusions.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></div>
<div class="card body sticky"><h3>Departure dates</h3>${t.dates.length?t.dates.map(d=>`<p>${fd(d)} ${waBtn('Enquiry: '+t.name+' departing '+fd(d),'Enquire')}</p>`).join(''):'<p class="muted">Dates on request.</p>'}<p>${waBtn('Hi, I am interested in '+t.name,'Chat on WhatsApp','btn wa')}</p><p class="muted">Prices are per person on twin sharing. Subject to season.</p></div></div>
<h2 style="margin-top:36px">You may also like</h2><div class="grid">${rel.map(tourCard).join('')}</div></section>`}

/* ---------- admin ---------- */
const S={
 tour:{coll:'tours',f:[['name','Tour name'],['price','Price per person (INR)','number'],['route','Route (use place names)'],['highlights','Highlights (comma separated)','list'],['dates','Departure dates YYYY-MM-DD (comma separated)','dates'],['itinerary','Itinerary, one day per line as "Title: description"','lines'],['inclusions','Inclusions (comma separated)','list'],['status','Status','select',['live','draft']],['seoTitle','SEO title'],['seoDesc','SEO description','area']]},
 flight:{coll:'flights',f:[['route','Route'],['airline','Airline'],['no','Flight no.'],['dep','Departure','time'],['arr','Arrival','time'],['price','Fare (INR)','number'],['seats','Seats left','number'],['days','Operating days']]},
 post:{coll:'posts',f:[['title','Title'],['slug','URL slug'],['excerpt','Short summary','area'],['body','Article','area'],['status','Status','select',['live','draft']]]},
 review:{coll:'reviews',f:[['name','Name'],['trip','Trip'],['rating','Rating 1 to 5','number'],['text','Review','area']]}
};
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const val=(o,n,ty)=>{const v=o[n];return ty==='list'||ty==='dates'?(v||[]).join(', '):ty==='lines'?(v||[]).join('\n'):v??''};
function input([n,l,ty='text',opt],o){const v=esc(val(o,n,ty));if(ty==='area'||ty==='lines')return `<label>${l}</label><textarea name="${n}" ${ty==='lines'?'style="min-height:160px"':''}>${v}</textarea>`;if(ty==='select')return `<label>${l}</label><select name="${n}">${opt.map(x=>`<option ${x===o[n]?'selected':''}>${x}</option>`).join('')}</select>`;return `<label>${l}</label><input name="${n}" type="${ty==='list'||ty==='dates'||ty==='lines'?'text':ty}" value="${v}">`}
function openForm(kind,id){const sc=S[kind],arr=D[sc.coll],o=id==='new'?{}:arr.find(x=>x.id==id);
 const m=document.createElement('div');m.className='modal';m.innerHTML=`<form class="card"><h3>${id==='new'?'Add':'Edit'} ${kind}</h3>${sc.f.map(f=>input(f,o)).join('')}<p><button class="btn">Save</button> <button type="button" class="btn alt" data-close>Cancel</button></p></form>`;document.body.appendChild(m);
 m.querySelector('[data-close]').onclick=()=>m.remove();
 m.querySelector('form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),r={};
  sc.f.forEach(([n,,ty])=>{const v=f[n];r[n]=ty==='number'?+v:ty==='list'?v.split(',').map(s=>s.trim()).filter(Boolean):ty==='dates'?v.split(',').map(s=>s.trim()).filter(s=>/^\d{4}-\d{2}-\d{2}$/.test(s)):ty==='lines'?v.split('\n').map(s=>s.trim()).filter(Boolean):v});
  if(kind==='tour'){r.days=r.itinerary.length;if(!o.id){r.hue=Math.floor(Math.random()*360);r.photo=r.name}if(!o.slug)r.slug=slug(r.name)}
  if(kind==='post'&&!r.slug)r.slug=slug(r.title);
  if(o.id)Object.assign(o,r);else arr.push({id:Date.now(),...r});save();m.remove();render()};}
const tbl=(h,rows)=>`<div class="tablewrap"><table><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr>${rows}</table></div>`;
const acts=(k,id,own)=>`<button class="btn sm alt" data-edit="${k}:${id}">Edit</button> ${own?`<button class="btn sm alt" data-del="${k}:${id}">Delete</button>`:''}`;
function seoHealth(){const l=[];D.tours.filter(t=>t.status==='live').forEach(t=>{if(!t.seoTitle||t.seoTitle.length>60)l.push(`Tour “${t.name}”: SEO title missing or over 60 characters`);if(!t.seoDesc||t.seoDesc.length>160)l.push(`Tour “${t.name}”: SEO description missing or over 160 characters`)});return l}
function admin(){
 if(!session)return `<section class="sec wrap"><div class="card body" style="max-width:400px;margin:auto"><h2>Admin login</h2><p class="muted">Demo only. Pick a role to see what each can do. The real build uses secure email login.</p><button class="btn" data-login="owner">Login as Owner</button> <button class="btn alt" data-login="staff">Login as Staff</button></div></section>`;
 const own=session.role==='owner',T=[['overview','Overview'],['tours','Tours and prices'],['flights','Flights'],['enquiries','Enquiries'],['posts','Blog'],['reviews','Reviews'],['seo','SEO'],...(own?[['settings','Users and settings']]:[])];
 const B={
  overview:()=>{const h=seoHealth();return `<div class="stats"><div class="card stat">Live tours<b>${live().length}/${D.tours.length}</b></div><div class="card stat">Flights<b>${D.flights.length}</b></div><div class="card stat">New enquiries<b>${D.enquiries.filter(e=>e.status==='new').length}</b></div><div class="card stat">SEO issues<b>${h.length}</b></div></div><h3>SEO health</h3>${h.length?`<ul>${h.map(x=>`<li class="bad">${esc(x)}</li>`).join('')}</ul>`:'<p class="ok">All live tours have SEO titles and descriptions.</p>'}<p class="muted">Try it: edit a tour price, then open the public Tours page to see it change instantly.</p>`},
  tours:()=>`<p><button class="btn sm" data-edit="tour:new">+ Add tour</button></p>`+tbl(['Tour','Days','Price','Dates','Status',''],D.tours.map(t=>`<tr><td>${esc(t.name)}</td><td>${dayN(t)}</td><td>${inr(t.price)}</td><td>${t.dates.length}</td><td><span class="badge ${t.status==='live'?'':'off'}">${t.status}</span></td><td>${acts('tour',t.id,own)}</td></tr>`).join('')),
  flights:()=>`<p><button class="btn sm" data-edit="flight:new">+ Add flight</button></p>`+tbl(['Route','Flight','Time','Days','Fare','Seats',''],D.flights.map(f=>`<tr><td>${esc(f.route)}</td><td>${esc(f.airline)} ${esc(f.no)}</td><td>${esc(f.dep)} to ${esc(f.arr)}</td><td>${esc(f.days)}</td><td>${inr(f.price)}</td><td>${f.seats}</td><td>${acts('flight',f.id,own)}</td></tr>`).join('')),
  enquiries:()=>tbl(['Name','Interest','When','Pax','Status'],D.enquiries.map(e=>`<tr><td>${esc(e.name)}</td><td>${esc(e.tour)}</td><td>${esc(e.when)}</td><td>${e.pax}</td><td><select data-enq="${e.id}">${['new','contacted','booked','lost'].map(s=>`<option ${s===e.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')),
  posts:()=>`<p><button class="btn sm" data-edit="post:new">+ New post</button></p>`+tbl(['Title','Status',''],D.posts.map(p=>`<tr><td>${esc(p.title)}</td><td>${p.status}</td><td>${acts('post',p.id,own)}</td></tr>`).join('')),
  reviews:()=>`<p><button class="btn sm" data-edit="review:new">+ Add review</button></p>`+tbl(['Name','Trip','Rating',''],D.reviews.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.trip)}</td><td>${stars(r.rating)}</td><td>${acts('review',r.id,own)}</td></tr>`).join('')),
  seo:()=>`<p class="muted">Edit the Google title and description for each page. Green means a good length.</p><form id="seof">${Object.keys(D.seo).map(k=>{const s=D.seo[k];return `<div class="card body" style="margin-bottom:12px"><b>${k}</b><label>Title</label><input name="t_${k}" value="${esc(s.t)}" oninput="this.nextElementSibling.textContent=this.value.length+'/60'"><span class="muted">${s.t.length}/60</span><label>Description</label><textarea name="d_${k}" oninput="this.nextElementSibling.textContent=this.value.length+'/160'">${esc(s.d)}</textarea><span class="muted">${s.d.length}/160</span><div class="snip"><u>${esc(s.t)}</u><i>bhutanz.com › ${k}</i><br><span>${esc(s.d)}</span></div></div>`}).join('')}<button class="btn">Save SEO</button></form>`,
  settings:()=>`<h3>Users</h3>${tbl(['Name','Role'],D.users.map(u=>`<tr><td>${u.name}</td><td>${u.role}</td></tr>`).join(''))}<p class="muted">Owner can invite staff. Staff can edit tours, prices, dates, flights, blog and enquiries but cannot delete or manage users.</p><h3>Business details</h3><form id="set">${[['wa','WhatsApp number with country code'],['phone','Phone'],['email','Email'],['address','Address']].map(([n,l])=>`<label>${l}</label><input name="${n}" value="${esc(D.settings[n])}">`).join('')}<p><button class="btn sm">Save</button> <button type="button" class="btn sm alt" data-reset>Reset demo data</button></p></form>`
 }[tab]();
 return `<div class="wrap admin"><aside class="side card body"><p class="muted">Signed in as <b>${session.role}</b></p>${T.map(([k,l])=>`<a href="#/admin" data-tab="${k}" class="${k===tab?'on':''}">${l}</a>`).join('')}<a href="#/" >← View public site</a><a href="#/admin" data-logout>Logout</a></aside><div style="min-width:0">${B}</div></div>`}

/* ---------- router ---------- */
function render(keep){const h=location.hash.replace('#/','')||'home',[p,arg]=h.split('/');
 if(p!=='admin')setMeta('La Bhutanz Tours','');
 $('#app').innerHTML=p==='tour'?tourPage(arg):p==='post'?post(arg):p==='destination'?destPage(arg):p==='admin'?(setMeta('Admin | La Bhutanz',''),admin()):(pages[p]||pages.notfound)();
 $('#foot').innerHTML=`<div class="wrap two"><div><h3>La Bhutanz Tours</h3><p style="opacity:.8">Mumbai-based Bhutan specialists. Licensed Bhutan partners, private guides, handpicked stays.</p><p>${esc(D.settings.address)}<br>${esc(D.settings.phone)} · ${esc(D.settings.email)}</p></div><div><a href="#/tours">All tours</a><br><a href="#/destinations">Destinations</a><br><a href="#/flights">Flights</a><br><a href="#/blog">Blog</a><br><a href="#/faq">FAQ</a><br><a href="#/plan">Plan my trip</a></div></div>`;
 $('#wafloat').href=wa('Hi, I want to plan a Bhutan trip.');if(!keep)scrollTo(0,0)}
function addEnq(n,t,w,p){D.enquiries.unshift({id:Date.now(),name:n,tour:t,when:w||'Flexible',pax:+p||2,status:'new'});save()}
document.addEventListener('click',e=>{const t=e.target.closest('[data-login],[data-tab],[data-logout],[data-edit],[data-del],[data-reset],[data-clear]');if(!t)return;const d=t.dataset;
 if(d.login){session={role:d.login};tab='overview';e.preventDefault();render()}
 else if(d.tab){tab=d.tab;e.preventDefault();render()}
 else if('logout' in d){session=null;e.preventDefault();render()}
 else if(d.edit){const[k,i]=d.edit.split(':');openForm(k,i)}
 else if('clear' in d){F={dest:'',days:'',budget:'',sort:''};render(1)}
 else if('reset' in d){if(confirm('Reset all demo data?')){D=structuredClone(SEED);save();render()}}
 else if(d.del&&confirm('Delete this item?')){const[k,i]=d.del.split(':'),c=S[k].coll;D[c]=D[c].filter(x=>x.id!=i);save();render()}});
document.addEventListener('change',e=>{const d=e.target.dataset;if(d.enq){D.enquiries.find(x=>x.id==d.enq).status=e.target.value;save()}if(d.f){F[d.f]=e.target.value;if(!e.target.closest("#hs"))render(1)}});
document.addEventListener('submit',e=>{const id=e.target.id;
 if(id==='hs'){e.preventDefault();location.hash='#/tours'}
 if(id==='enq'){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));addEnq(f.n,f.t,f.m,f.p);open(wa(`Hi, I'm ${f.n}. Interested in "${f.t}" for ${f.p} travellers in ${f.m||'flexible dates'}. Budget: ${f.b}. ${f.x}`),'_blank')}
 if(id==='set'){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.wa=f.wa.replace(/\D/g,'');Object.assign(D.settings,f);save();alert('Saved');render()}
 if(id==='seof'){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));Object.keys(D.seo).forEach(k=>D.seo[k]={t:f['t_'+k],d:f['d_'+k]});save();alert('SEO saved');render()}});
addEventListener('hashchange',render);render();
