// First-run database for Skyland Tours & Travels. Everything here is editable in the admin panel.
// Prices start at 0 ("Price on request"); contact details start empty and are entered in Admin → Settings.
const fs = require('fs'), path = require('path');
const IMG = path.join(__dirname, '..', 'public', 'img');
const has = f => fs.existsSync(path.join(IMG, f));
const img = f => (has(f) ? '/img/' + f : '');

/* ---------- destinations ---------- */
const D = (slug, name, state, region, tagline, bestTime, description, highlights) => ({
  id: slug, slug, name, state, region, tagline, bestTime, description, highlights,
  image: img('destinations/' + slug + '.jpg'), active: true
});
const destinations = [
  D('kerala', 'Kerala', 'Kerala', 'South', 'Backwaters, tea hills and Ayurveda', 'September to March',
    'God’s Own Country mixes palm-fringed backwaters, misty tea estates in Munnar, wildlife at Periyar and a long Arabian Sea coastline. Slow houseboat cruises and Ayurvedic stays make it India’s favourite honeymoon and family destination.',
    ['Houseboat cruise in Alleppey', 'Munnar tea gardens', 'Periyar boat safari', 'Fort Kochi heritage walk']),
  D('goa', 'Goa', 'Goa', 'West', 'Sun, sand and Portuguese heritage', 'November to February',
    'Goa pairs lively North Goa beaches with the quieter sands of the south, centuries-old churches in Old Goa, spice plantations and a food scene shaped by Portuguese and Konkan cooking.',
    ['Baga to Vagator beach hopping', 'Old Goa churches (UNESCO)', 'Fontainhas Latin Quarter', 'Dudhsagar Falls']),
  D('rajasthan', 'Jaipur & Rajasthan', 'Rajasthan', 'North', 'Forts, palaces and living traditions', 'October to March',
    'The Pink City of Jaipur anchors Rajasthan’s royal circuit, with Amber Fort, the City Palace, Hawa Mahal and Jantar Mantar, and lively bazaars selling jewellery, block prints and blue pottery.',
    ['Amber Fort', 'City Palace and Jantar Mantar', 'Hawa Mahal', 'Johari Bazaar shopping']),
  D('udaipur', 'Udaipur', 'Rajasthan', 'North', 'The City of Lakes', 'October to March',
    'Udaipur wraps palaces, havelis and temples around Lake Pichola and the Aravalli hills. Sunset boat rides, the City Palace complex and the old-town lanes make it Rajasthan’s most romantic stop.',
    ['City Palace complex', 'Lake Pichola boat ride', 'Jagdish Temple', 'Bagore Ki Haveli']),
  D('jaisalmer', 'Jaisalmer', 'Rajasthan', 'North', 'The Golden City on the edge of the Thar', 'October to February',
    'Jaisalmer’s sandstone fort is still a living town, with homes, shops and temples inside the walls. Nearby Sam sand dunes offer camel safaris, folk music and nights in desert camps.',
    ['Jaisalmer Fort', 'Patwon Ki Haveli', 'Sam Sand Dunes camel safari', 'Gadisar Lake']),
  D('agra', 'Agra & Delhi', 'Uttar Pradesh / Delhi', 'North', 'The Taj Mahal and India’s capital', 'October to March',
    'Agra’s Taj Mahal, Agra Fort and Fatehpur Sikri sit a few hours from Delhi’s Red Fort, Humayun’s Tomb and Old Delhi bazaars, which is why Delhi–Agra–Jaipur remains the classic first trip to India.',
    ['Taj Mahal at sunrise or sunset', 'Agra Fort', 'Fatehpur Sikri', 'Humayun’s Tomb and Old Delhi']),
  D('himachal', 'Himachal Pradesh', 'Himachal Pradesh', 'North', 'Snow peaks, pine valleys and hill towns', 'March to June and September to November',
    'Shimla’s colonial charm, Manali’s Beas river valley and the adventure playground of Solang give Himachal something for every traveller. Winter brings snow; summer brings cool escapes from the plains.',
    ['Shimla Mall Road and Kufri', 'Kalka–Shimla toy train (UNESCO)', 'Solang Valley activities', 'Hadimba Temple and Old Manali']),
  D('kashmir', 'Kashmir', 'Jammu & Kashmir', 'North', 'Shikaras, gardens and snow meadows', 'April to October (Gulmarg skiing December to February)',
    'Srinagar’s Dal Lake and Mughal gardens, the Gulmarg gondola, and the green valleys of Pahalgam and Sonamarg make Kashmir one of India’s most scenic regions. We follow local travel advisories closely before every departure.',
    ['Shikara ride on Dal Lake', 'Mughal gardens of Srinagar', 'Gulmarg gondola', 'Pahalgam valleys']),
  D('ladakh', 'Ladakh', 'Ladakh', 'North', 'High-altitude lakes, monasteries and mountain passes', 'June to September',
    'Leh sits at about 3,500 metres, with Buddhist monasteries, the Nubra Valley’s sand dunes and the colour-changing Pangong Tso. Itineraries include rest days so your body can adjust to the altitude.',
    ['Pangong Tso', 'Nubra Valley and Hunder dunes', 'Khardung La', 'Thiksey and Hemis monasteries']),
  D('uttarakhand', 'Uttarakhand', 'Uttarakhand', 'North', 'Ganga, yoga and Himalayan foothills', 'March to June and September to November',
    'Rishikesh and Haridwar sit where the Ganga leaves the mountains, offering aartis, yoga ashrams and white-water rafting. Higher up, Mussoorie, Nainital and Auli bring hill-station views and Himalayan panoramas.',
    ['Ganga Aarti at Haridwar and Rishikesh', 'White-water rafting', 'Yoga and meditation', 'Neelkanth Mahadev Temple']),
  D('varanasi', 'Varanasi', 'Uttar Pradesh', 'North', 'The spiritual capital on the Ganga', 'October to March',
    'One of the world’s oldest living cities, Varanasi is known for sunrise boat rides past its ghats, the evening Ganga Aarti, the Kashi Vishwanath Temple and nearby Sarnath, where the Buddha gave his first sermon.',
    ['Sunrise boat ride on the Ganga', 'Ganga Aarti at Dashashwamedh Ghat', 'Kashi Vishwanath Temple', 'Sarnath']),
  D('amritsar', 'Amritsar', 'Punjab', 'North', 'The Golden Temple and Punjabi hospitality', 'October to March',
    'Amritsar is home to Harmandir Sahib (the Golden Temple), whose community kitchen feeds thousands daily. Add Jallianwala Bagh, the Partition Museum and the Wagah border ceremony, and Punjab’s rich food.',
    ['Golden Temple and langar', 'Wagah Border ceremony', 'Jallianwala Bagh', 'Partition Museum']),
  D('andaman', 'Andaman Islands', 'Andaman & Nicobar Islands', 'Islands', 'Turquoise water and white-sand beaches', 'October to May',
    'Port Blair’s Cellular Jail, Havelock’s Radhanagar Beach and Neil Island’s coral shallows give the Andamans a mix of history and island leisure, with snorkelling and scuba for beginners.',
    ['Radhanagar Beach', 'Elephant Beach snorkelling', 'Cellular Jail light and sound show', 'Neil Island beaches']),
  D('sikkim-darjeeling', 'Sikkim & Darjeeling', 'Sikkim / West Bengal', 'North-East', 'Kanchenjunga views and tea gardens', 'March to May and October to December',
    'Gangtok’s monasteries and mountain lakes, Pelling’s Kanchenjunga viewpoints and Darjeeling’s tea estates and toy train show the Eastern Himalayas at their greenest.',
    ['Kanchenjunga sunrise', 'Tsomgo Lake', 'Darjeeling Himalayan Railway (UNESCO)', 'Tea garden visit']),
  D('meghalaya', 'Meghalaya', 'Meghalaya', 'North-East', 'The abode of clouds', 'October to May (waterfalls peak June to September)',
    'Meghalaya’s living root bridges, thundering waterfalls near Cherrapunji, caves and the glass-clear Umngot river at Dawki make it the Northeast’s most rewarding short trip.',
    ['Double-decker living root bridge', 'Nohkalikai Falls', 'Dawki river boating', 'Mawlynnong village']),
  D('tamil-nadu', 'Tamil Nadu', 'Tamil Nadu', 'South', 'Temple towns and the southern tip of India', 'November to February',
    'Tamil Nadu’s Dravidian temples, from Madurai’s Meenakshi Amman Temple to Thanjavur’s Brihadisvara Temple and Mahabalipuram’s Shore Temple, sit alongside French Pondicherry and the sunrise point at Kanyakumari.',
    ['Meenakshi Amman Temple, Madurai', 'Brihadisvara Temple, Thanjavur (UNESCO)', 'Shore Temple, Mahabalipuram (UNESCO)', 'Kanyakumari sunrise']),
  D('karnataka', 'Karnataka', 'Karnataka', 'South', 'Palaces, ruins and coffee hills', 'October to March',
    'Mysuru’s illuminated palace, the boulder-strewn ruins of Hampi, Coorg’s coffee estates and the Hoysala temples of Belur and Halebidu make Karnataka a deep, varied heritage destination.',
    ['Mysuru Palace', 'Hampi ruins (UNESCO)', 'Coorg coffee estates', 'Belur and Halebidu temples']),
  D('gujarat-kutch', 'Kutch, Gujarat', 'Gujarat', 'West', 'The White Rann and Kutch craft villages', 'November to February',
    'The Great Rann of Kutch turns into a vast white salt desert after the monsoon. The seasonal Rann Utsav tent city, Bhuj’s palaces and nearby craft villages of embroidery and block printing complete the trip.',
    ['White Rann at sunset', 'Rann Utsav tent city (seasonal)', 'Aina Mahal and Prag Mahal, Bhuj', 'Craft villages']),
];

/* ---------- packages ---------- */
const INC = [
  'Hotel stays on twin-sharing basis, in the category you choose',
  'Daily breakfast (other meals only where mentioned)',
  'Private air-conditioned vehicle with driver for transfers and sightseeing as per the itinerary',
  'Airport / railway station pick-up and drop',
  'Toll, parking and driver allowances',
  'A Skyland trip coordinator on call during your journey'
];
const EXC = [
  'Flights or train tickets to and from the starting point (can be arranged on request)',
  'Meals not mentioned in the itinerary',
  'Monument, park and activity entry fees, camera fees and optional activities',
  'Personal expenses such as laundry, tips, porter charges and travel insurance',
  'GST and any government permit fees, where applicable',
  'Anything not listed under inclusions'
];
const IDEAL = {
  heritage: ['First-time visitors to India who want the highlights', 'Families and friends travelling together', 'History, architecture and photography lovers'],
  hills: ['Travellers who like mountain air and scenic drives', 'Families looking for a cool-weather escape', 'Couples and groups of friends'],
  beach: ['Couples and families who want a relaxed break', 'Travellers who enjoy water activities', 'Short-break holidaymakers'],
  honeymoon: ['Newly-weds looking for privacy and romance', 'Couples celebrating an anniversary', 'Anyone who prefers an unhurried pace'],
  adventure: ['Active travellers who enjoy outdoors and trekking', 'Groups of friends and solo travellers', 'Those comfortable with long drives and altitude'],
  spiritual: ['Pilgrims and senior travellers', 'Families travelling across generations', 'Travellers interested in culture and rituals'],
  family: ['Families with children', 'Multi-generation groups', 'Travellers who want comfortable, well-paced days']
};
const P = (id, theme, name, nights, destSlugs, route, summary, intro, highlights, days, featured) => ({
  id, slug: id, category: theme, name, nights, days: nights + 1, price: 0, singleSupplement: 0,
  stay: route, summary, intro, highlights,
  itinerary: days.map(([title, desc]) => ({ title, meta: '', desc })),
  inclusions: INC, exclusions: EXC, ideal: IDEAL[theme] || IDEAL.family, faqs: [],
  image: img('packages/' + id + '.jpg'), destinations: destSlugs, flightIncluded: false,
  featured: !!featured, active: true, order: 0, priceConfirmed: false
});
const packages = [
  P('golden-triangle-6d', 'heritage', 'Golden Triangle: Delhi, Agra & Jaipur', 5, ['agra', 'rajasthan'], 'Delhi 2N · Agra 1N · Jaipur 2N',
    'India’s classic first trip: Delhi’s monuments, the Taj Mahal and Jaipur’s palaces.',
    'The Golden Triangle covers three of India’s most visited cities in six days, with comfortable driving distances and time to enjoy each stop. The Taj Mahal is closed on Fridays, so we plan the order of your days around it.',
    ['Taj Mahal and Agra Fort', 'Old and New Delhi sightseeing', 'Amber Fort and City Palace, Jaipur', 'Fatehpur Sikri stop on the way'],
    [['Arrive in Delhi', 'Meet our representative at the airport or station and transfer to your hotel. Evening free to rest or explore a local market.'],
     ['Delhi sightseeing', 'Visit Humayun’s Tomb, India Gate and the Qutub Minar, drive past Rashtrapati Bhavan, and explore Old Delhi’s bazaars and Jama Masjid.'],
     ['Delhi to Agra', 'Drive to Agra (about 4 hours). Visit Agra Fort and see the Taj Mahal at sunset, or the next morning if you prefer.'],
     ['Agra to Jaipur via Fatehpur Sikri', 'Stop at the red-sandstone ruins of Fatehpur Sikri, then continue to Jaipur (about 5 hours in total).'],
     ['Jaipur sightseeing', 'Amber Fort, the City Palace, Jantar Mantar and a photo stop at Hawa Mahal. Time for shopping in Johari Bazaar.'],
     ['Departure', 'Transfer to Jaipur airport or station, or continue to Delhi (about 5 hours) for your onward journey.']], true),
  P('royal-rajasthan-8d', 'heritage', 'Royal Rajasthan: Jaipur, Pushkar, Jodhpur & Udaipur', 7, ['rajasthan', 'udaipur'], 'Jaipur 2N · Pushkar 1N · Jodhpur 2N · Udaipur 2N',
    'Forts, palaces and lakes across four royal cities.',
    'This circuit follows the old royal routes of Rajasthan, from Jaipur’s pink palaces to Jodhpur’s blue-washed old town and Udaipur’s lakeside City Palace, with a stop at the holy lake of Pushkar.',
    ['Amber Fort and City Palace, Jaipur', 'Mehrangarh Fort, Jodhpur', 'Ranakpur Jain temples', 'Sunset boat ride at Lake Pichola'],
    [['Arrive in Jaipur', 'Airport or station pick-up and hotel check-in. Evening at leisure.'],
     ['Jaipur sightseeing', 'Amber Fort, City Palace, Jantar Mantar and Hawa Mahal, followed by the bazaars.'],
     ['Jaipur to Pushkar', 'Drive to Pushkar (about 3 hours) via Ajmer. Visit the Brahma Temple and walk the lakeside ghats.'],
     ['Pushkar to Jodhpur', 'Drive to Jodhpur (about 3.5 hours). Evening stroll in the old city around the Clock Tower market.'],
     ['Jodhpur sightseeing', 'Mehrangarh Fort, Jaswant Thada and the blue lanes of Brahmpuri, with time for spice and handicraft shopping.'],
     ['Jodhpur to Udaipur via Ranakpur', 'Visit the marble Jain temples of Ranakpur on the way (about 6 hours of driving in total) and reach Udaipur by evening.'],
     ['Udaipur sightseeing', 'City Palace, Jagdish Temple and Saheliyon Ki Bari, then a sunset boat ride on Lake Pichola.'],
     ['Departure', 'Transfer to Udaipur airport or station for your onward journey.']], true),
  P('kerala-backwaters-7d', 'family', 'Kerala Backwaters & Hills', 6, ['kerala'], 'Kochi 1N · Munnar 2N · Thekkady 1N · Alleppey 1N · Kochi 1N',
    'Tea hills, a wildlife lake and a night on a houseboat.',
    'A relaxed loop through Kerala’s highlights: Fort Kochi, the tea estates of Munnar, the spice country of Thekkady and an overnight houseboat cruise on the Alleppey backwaters.',
    ['Munnar tea gardens', 'Periyar Lake boat ride', 'Overnight houseboat in Alleppey', 'Fort Kochi heritage walk'],
    [['Arrive in Kochi', 'Pick-up and hotel check-in. Evening walk in Fort Kochi to see the Chinese fishing nets and St Francis Church.'],
     ['Kochi to Munnar', 'Drive to Munnar (about 4 to 5 hours) through rubber and spice country, with waterfall stops on the way.'],
     ['Munnar sightseeing', 'Tea plantations, a tea museum visit, Mattupetty Dam and Echo Point, with time for an optional Eravikulam National Park visit.'],
     ['Munnar to Thekkady', 'Drive to Thekkady (about 4 hours). Spice plantation walk in the afternoon.'],
     ['Thekkady to Alleppey houseboat', 'Morning boat ride on Periyar Lake, then drive to Alleppey and board your houseboat for lunch, an evening cruise and an overnight stay.'],
     ['Alleppey to Kochi', 'Disembark after breakfast and drive to Kochi (about 2 hours). Afternoon at leisure.'],
     ['Departure', 'Transfer to Kochi airport or station.']], true),
  P('munnar-alleppey-honeymoon-6d', 'honeymoon', 'Kerala Honeymoon: Munnar, Alleppey & Kovalam', 5, ['kerala'], 'Munnar 2N · Alleppey 1N · Kovalam 2N',
    'Misty hills, a private houseboat and a beachside finish.',
    'Designed for couples, this itinerary moves from cool tea hills to a private houseboat on the backwaters and ends with two relaxed nights by the sea at Kovalam.',
    ['Munnar tea estates', 'Private houseboat stay', 'Kovalam beach days', 'Optional Ayurvedic massage'],
    [['Arrive in Kochi and drive to Munnar', 'Airport pick-up and a scenic drive (about 4 to 5 hours) to your hill-resort in Munnar.'],
     ['Munnar at leisure', 'Visit tea plantations, Mattupetty Dam and viewpoints, or simply enjoy the resort.'],
     ['Munnar to Alleppey houseboat', 'Drive to Alleppey (about 4.5 hours) and board your private houseboat for an evening cruise and candle-lit dinner on board.'],
     ['Alleppey to Kovalam', 'Disembark after breakfast and drive to Kovalam (about 4 hours). Sunset on the beach.'],
     ['Kovalam beach day', 'Relax on Lighthouse Beach or Hawa Beach. Optional Ayurvedic spa session.'],
     ['Departure', 'Transfer to Thiruvananthapuram airport (about 30 minutes).']]),
  P('goa-beach-break-5d', 'beach', 'Goa Beach Break', 4, ['goa'], 'North Goa 2N · South Goa 2N',
    'North and South Goa beaches, heritage churches and sunsets.',
    'Spend two nights on lively North Goa and two on the quieter south, with sightseeing in Old Goa and plenty of free time for the beach.',
    ['Baga, Calangute and Anjuna beaches', 'Old Goa churches (UNESCO)', 'Fort Aguada and Chapora views', 'Palolem or Colva beach day'],
    [['Arrive in Goa', 'Pick-up from Dabolim or Mopa airport and check in. Evening at the beach.'],
     ['North Goa tour', 'Fort Aguada, Calangute, Baga and Anjuna beaches, and a sunset at Vagator. Optional water sports.'],
     ['Old Goa and move to South Goa', 'Visit the Basilica of Bom Jesus and Se Cathedral, then transfer to your South Goa hotel and relax by the sea.'],
     ['South Goa at leisure', 'Colva, Benaulim or Palolem beach, or an optional spice plantation visit and Dudhsagar excursion.'],
     ['Departure', 'Transfer to the airport or railway station.']], true),
  P('kashmir-paradise-7d', 'hills', 'Kashmir Paradise: Srinagar, Gulmarg & Pahalgam', 6, ['kashmir'], 'Srinagar 3N · Gulmarg 1N · Pahalgam 2N',
    'Dal Lake, Mughal gardens and snow meadows.',
    'This Kashmir valley circuit covers Srinagar’s lake and gardens, the high meadows of Gulmarg and the pine-lined river valleys of Pahalgam. We review local travel advisories before every departure.',
    ['Shikara ride on Dal Lake', 'Shalimar and Nishat gardens', 'Gulmarg gondola', 'Betaab Valley and Aru, Pahalgam'],
    [['Arrive in Srinagar', 'Transfer to your hotel or houseboat. Evening shikara ride on Dal Lake.'],
     ['Srinagar sightseeing', 'Mughal gardens (Shalimar, Nishat, Chashme Shahi), Shankaracharya Temple viewpoint and the old-city markets.'],
     ['Srinagar to Gulmarg', 'Drive to Gulmarg (about 2 hours) and ride the Gulmarg Gondola (subject to weather). Overnight in Gulmarg.'],
     ['Gulmarg to Pahalgam', 'Drive to Pahalgam (about 4 to 5 hours), visiting saffron fields at Pampore on the way.'],
     ['Pahalgam sightseeing', 'Betaab Valley, Aru Valley and Chandanwari (subject to access), with pony rides available.'],
     ['Pahalgam to Srinagar', 'Return to Srinagar (about 3 hours). Free evening for shopping in the Lal Chowk area.'],
     ['Departure', 'Transfer to Srinagar airport (about 30 minutes).']]),
  P('ladakh-adventure-8d', 'adventure', 'Ladakh Adventure: Leh, Nubra & Pangong', 7, ['ladakh'], 'Leh 4N · Nubra 2N · Pangong 1N',
    'High passes, desert dunes and a lake that changes colour.',
    'A classic Ladakh circuit with rest days built in for acclimatisation. You cross Khardung La, camp among the Hunder dunes and watch the light change on Pangong Tso. Permits are arranged by us.',
    ['Khardung La (5,359 m)', 'Hunder sand dunes and camel ride', 'Pangong Tso overnight', 'Thiksey and Hemis monasteries'],
    [['Arrive in Leh', 'Fly to Leh (about 3,500 m). Rest all day to acclimatise; light walk only.'],
     ['Leh local sightseeing', 'Shanti Stupa, Leh Palace and the main bazaar. Another gentle day for altitude adjustment.'],
     ['Leh to Nubra Valley', 'Cross Khardung La and descend to Nubra (about 5 to 6 hours). Overnight in a camp or hotel.'],
     ['Nubra Valley', 'Camel ride on the Hunder dunes, Diskit Monastery and the large Maitreya Buddha statue.'],
     ['Nubra to Pangong Tso', 'Drive along the Shyok river to Pangong (about 6 to 7 hours). Sunset at the lake.'],
     ['Pangong to Leh', 'Sunrise by the lake, then cross Chang La and return to Leh (about 5 hours).'],
     ['Leh monasteries', 'Thiksey and Hemis monasteries, Shey Palace, and Sangam where the Indus and Zanskar meet.'],
     ['Departure', 'Transfer to Leh airport.']], true),
  P('manali-shimla-7d', 'hills', 'Shimla & Manali Hill Escape', 6, ['himachal'], 'Shimla 2N · Manali 3N · Chandigarh 1N',
    'Colonial hill town, river valley and snow-peak views.',
    'Combine Shimla’s colonial streets with Manali’s mountain scenery. Add the Solang valley, the Atal Tunnel to Sissu and, in winter, snow activities.',
    ['Mall Road and Kufri, Shimla', 'Solang Valley', 'Hadimba Temple and Old Manali', 'Atal Tunnel and Sissu'],
    [['Arrive in Chandigarh and drive to Shimla', 'Drive to Shimla (about 3 to 4 hours). Evening on the Mall Road.'],
     ['Shimla sightseeing', 'Kufri, The Ridge, Christ Church and Jakhu Temple. Optional toy-train ride on the Kalka–Shimla line (subject to availability).'],
     ['Shimla to Manali', 'Drive to Manali (about 7 to 8 hours) along the Beas river and through the Kullu valley.'],
     ['Manali local', 'Hadimba Temple, Vashisht hot springs, Old Manali cafes and the Mall Road.'],
     ['Solang Valley and Sissu', 'Adventure activities at Solang (paragliding, zorbing, snow activities in season) and a drive through the Atal Tunnel to Sissu.'],
     ['Manali to Chandigarh', 'Return drive (about 8 to 9 hours) to Chandigarh for an overnight stay.'],
     ['Departure', 'Transfer to Chandigarh airport or railway station.']]),
  P('rishikesh-rafting-yoga-5d', 'adventure', 'Rishikesh & Haridwar: Rafting, Yoga & Aarti', 4, ['uttarakhand'], 'Rishikesh 3N · Haridwar 1N',
    'White-water rafting, yoga sessions and evening Ganga Aarti.',
    'A short, energising trip on the Ganga: raft through rapids, join a yoga class, walk the famous suspension bridges and end with the evening aarti at Har Ki Pauri in Haridwar.',
    ['White-water rafting', 'Yoga and meditation session', 'Laxman Jhula and Ram Jhula', 'Ganga Aarti at Har Ki Pauri'],
    [['Arrive in Haridwar and move to Rishikesh', 'Pick-up and drive to Rishikesh (about 1 hour). Evening aarti at Triveni Ghat.'],
     ['Rishikesh sightseeing', 'Laxman Jhula, Ram Jhula, Parmarth Niketan and a relaxed café stroll. Yoga session in the morning.'],
     ['River rafting', 'Raft a stretch of the Ganga with trained guides (rafting runs from September to June, outside the monsoon). Afternoon free.'],
     ['Neelkanth Mahadev and Haridwar', 'Visit the Neelkanth Mahadev Temple, then move to Haridwar for the evening aarti at Har Ki Pauri.'],
     ['Departure', 'Morning temple visit if time permits, then transfer to Haridwar station or Dehradun airport.']]),
  P('varanasi-spiritual-trail-5d', 'spiritual', 'Varanasi & Ayodhya Spiritual Trail', 4, ['varanasi'], 'Varanasi 3N · Ayodhya 1N',
    'Ganga Aarti, sunrise boat rides, Sarnath and Ayodhya darshan.',
    'Experience Varanasi’s ghats at sunrise and sunset, visit Sarnath, then travel to Ayodhya for temple darshan before your departure from Lucknow.',
    ['Evening Ganga Aarti', 'Sunrise boat ride', 'Kashi Vishwanath darshan', 'Sarnath and Ayodhya temples'],
    [['Arrive in Varanasi', 'Pick-up and hotel check-in. Evening Ganga Aarti at Dashashwamedh Ghat.'],
     ['Varanasi ghats and temples', 'Sunrise boat ride, a walk along the ghats, Kashi Vishwanath, Annapurna and Sankat Mochan temples.'],
     ['Sarnath and local sights', 'Visit Sarnath’s stupas and museum, Bharat Mata Mandir and the silk-weaving lanes.'],
     ['Varanasi to Ayodhya', 'Drive to Ayodhya (about 5 hours). Evening visit to the ghats of the Sarayu river.'],
     ['Ayodhya darshan and departure', 'Morning temple visits, then drive to Lucknow (about 3 hours) for your onward journey.']]),
  P('amritsar-golden-temple-4d', 'spiritual', 'Amritsar: Golden Temple & Wagah Border', 3, ['amritsar'], 'Amritsar 3N',
    'The Golden Temple, Wagah border ceremony and Punjabi food.',
    'A compact trip built around Harmandir Sahib, with time for the Jallianwala Bagh memorial, the Partition Museum, the evening Beating Retreat at Wagah and Amritsar’s famous food.',
    ['Golden Temple and langar', 'Wagah Border ceremony', 'Jallianwala Bagh', 'Partition Museum'],
    [['Arrive in Amritsar', 'Pick-up and hotel check-in. Evening visit to the Golden Temple.'],
     ['Heritage and Wagah', 'Jallianwala Bagh, the Partition Museum and Gobindgarh Fort, then the Beating Retreat ceremony at the Attari–Wagah border.'],
     ['Golden Temple at dawn', 'Early-morning darshan, Durgiana Temple and a Punjabi food walk through the old city.'],
     ['Departure', 'Transfer to Amritsar airport or railway station.']]),
  P('andaman-island-escape-6d', 'beach', 'Andaman Island Escape: Port Blair, Havelock & Neil', 5, ['andaman'], 'Port Blair 2N · Havelock 2N · Neil 1N',
    'Radhanagar Beach, snorkelling and island ferries.',
    'Island-hop across the Andamans with inter-island ferries, beach days on Havelock and Neil, and an evening at the Cellular Jail in Port Blair.',
    ['Radhanagar Beach, Havelock', 'Elephant Beach snorkelling', 'Neil Island beaches', 'Cellular Jail light and sound show'],
    [['Arrive in Port Blair', 'Airport pick-up and hotel check-in. Evening visit to the Cellular Jail and its light and sound show.'],
     ['Port Blair to Havelock', 'Morning ferry to Havelock (Swaraj Dweep). Sunset at Radhanagar Beach.'],
     ['Havelock', 'Boat trip to Elephant Beach for snorkelling (weather permitting) and free time for optional scuba.'],
     ['Havelock to Neil Island', 'Ferry to Neil (Shaheed Dweep). Visit Bharatpur and Laxmanpur beaches.'],
     ['Neil to Port Blair', 'Return ferry to Port Blair. Evening visit to Corbyn’s Cove beach or the local market.'],
     ['Departure', 'Transfer to Port Blair airport.']], true),
  P('darjeeling-gangtok-7d', 'hills', 'Darjeeling & Sikkim: Gangtok, Pelling & Darjeeling', 6, ['sikkim-darjeeling'], 'Gangtok 3N · Pelling 1N · Darjeeling 2N',
    'Monasteries, mountain lakes and Kanchenjunga sunrise.',
    'Travel through Sikkim and the Darjeeling hills, with monasteries, high-altitude lakes, tea gardens, the toy train and a pre-dawn drive for a Kanchenjunga sunrise.',
    ['Tsomgo Lake', 'Pemayangtse Monastery, Pelling', 'Tiger Hill sunrise', 'Darjeeling toy train and tea estate'],
    [['Arrive in Bagdogra and drive to Gangtok', 'Transfer from Bagdogra airport or New Jalpaiguri station to Gangtok (about 4 to 5 hours).'],
     ['Gangtok sightseeing', 'Rumtek Monastery, Ganesh Tok, Hanuman Tok and the MG Marg promenade.'],
     ['Tsomgo Lake', 'Excursion to Tsomgo (Changu) Lake and Baba Mandir. Nathula Pass visits depend on permits and weather.'],
     ['Gangtok to Pelling', 'Drive to Pelling (about 5 hours) and enjoy views of the Kanchenjunga range.'],
     ['Pelling to Darjeeling', 'Visit Pemayangtse Monastery and Rabdentse ruins, then drive to Darjeeling (about 4 hours).'],
     ['Darjeeling sightseeing', 'Tiger Hill sunrise, Batasia Loop, Ghum Monastery, a tea-garden visit and a toy-train joyride (subject to availability).'],
     ['Departure', 'Drive to Bagdogra airport or New Jalpaiguri station (about 3 to 4 hours).']]),
  P('meghalaya-explorer-6d', 'adventure', 'Meghalaya Explorer: Shillong, Cherrapunji & Dawki', 5, ['meghalaya'], 'Shillong 3N · Sohra 1N · Guwahati 1N',
    'Living root bridges, waterfalls and the clearest river in India.',
    'Meghalaya rewards the curious: trek to a double-decker living root bridge, stand beside Nohkalikai Falls and take a boat on the transparent Umngot river at Dawki.',
    ['Double-decker living root bridge trek', 'Nohkalikai Falls and Mawsmai Cave', 'Dawki and Umngot river', 'Kamakhya Temple, Guwahati'],
    [['Arrive in Guwahati and drive to Shillong', 'Transfer to Shillong (about 3 to 3.5 hours). Evening walk around Ward’s Lake.'],
     ['Shillong sightseeing', 'Don Bosco Museum, Elephant Falls, Shillong Peak and the local markets.'],
     ['Shillong to Cherrapunji (Sohra)', 'Visit Nohkalikai Falls, Seven Sisters Falls and Mawsmai Cave. Overnight in Sohra.'],
     ['Living root bridge and Dawki', 'Trek to the double-decker root bridge at Nongriat (long stair descent; moderate fitness needed), then visit Mawlynnong and Dawki.'],
     ['Shillong to Guwahati', 'Drive to Guwahati and visit the Kamakhya Temple.'],
     ['Departure', 'Transfer to Guwahati airport.']]),
  P('tamil-nadu-temple-trail-8d', 'spiritual', 'Tamil Nadu Temple Trail', 7, ['tamil-nadu'], 'Mahabalipuram 1N · Pondicherry 1N · Thanjavur 1N · Madurai 2N · Rameswaram 1N · Kanyakumari 1N',
    'Dravidian temples from Mahabalipuram to Kanyakumari.',
    'A south-bound temple route through Tamil Nadu’s great monuments, with a night in French-influenced Pondicherry and an early morning at the southern tip of India.',
    ['Shore Temple, Mahabalipuram', 'Brihadisvara Temple, Thanjavur', 'Meenakshi Amman Temple, Madurai', 'Sunrise at Kanyakumari'],
    [['Arrive in Chennai and drive to Mahabalipuram', 'Pick-up and drive to Mahabalipuram (about 1.5 hours). Evening by the shore.'],
     ['Mahabalipuram to Pondicherry', 'Shore Temple and Five Rathas in the morning, then drive to Pondicherry (about 2 hours). Evening in the French Quarter.'],
     ['Pondicherry to Thanjavur', 'Visit Auroville’s Matrimandir viewpoint, then drive to Thanjavur (about 4.5 hours).'],
     ['Thanjavur to Madurai', 'Visit the Brihadisvara Temple and the Palace, then drive to Madurai (about 3.5 hours).'],
     ['Madurai sightseeing', 'Meenakshi Amman Temple and Thirumalai Nayak Palace, with the evening ritual at the temple.'],
     ['Madurai to Rameswaram', 'Drive to Rameswaram (about 3 hours). Visit the Ramanathaswamy Temple and, time permitting, Dhanushkodi.'],
     ['Rameswaram to Kanyakumari', 'Drive to Kanyakumari (about 5 to 6 hours). Sunset at the shore.'],
     ['Kanyakumari sunrise and departure', 'Sunrise, ferry to Vivekananda Rock Memorial, then transfer to Thiruvananthapuram airport (about 2 hours).']]),
  P('mysuru-coorg-escape-5d', 'family', 'Mysuru & Coorg Escape', 4, ['karnataka'], 'Mysuru 2N · Coorg 2N',
    'A royal palace city and a hill region of coffee estates.',
    'A relaxed Karnataka break from Bengaluru: the illuminated palace and bazaars of Mysuru, then two nights among the coffee and pepper estates of Coorg.',
    ['Mysuru Palace and Chamundi Hill', 'Namdroling Monastery, Bylakuppe', 'Abbey Falls and Raja’s Seat', 'Coffee estate walk'],
    [['Arrive in Bengaluru and drive to Mysuru', 'Pick-up and drive to Mysuru (about 3.5 hours). Evening at Brindavan Gardens (musical fountain timings vary).'],
     ['Mysuru sightseeing', 'Mysuru Palace, St Philomena’s Church, Chamundi Hill and Devaraja Market.'],
     ['Mysuru to Coorg', 'Stop at the Namdroling Monastery (Golden Temple) in Bylakuppe, then continue to Coorg (about 3 hours in total).'],
     ['Coorg sightseeing', 'Abbey Falls, Raja’s Seat, a coffee-estate walk and, optionally, the Dubare elephant camp.'],
     ['Departure', 'Drive to Bengaluru (about 5 to 6 hours) for your onward journey.']]),
  P('kutch-rann-utsav-5d', 'heritage', 'Kutch & the White Rann', 4, ['gujarat-kutch'], 'Bhuj 2N · Dhordo 1N · Bhuj 1N',
    'White salt desert, tent-city nights and craft villages.',
    'See the Great Rann of Kutch at sunset and sunrise, stay at the Dhordo tent city (open seasonally, usually November to February), and meet the artisans of Kutch’s craft villages.',
    ['White Rann at sunset and sunrise', 'Rann Utsav tent city (seasonal)', 'Aina Mahal and Prag Mahal', 'Embroidery and block-print villages'],
    [['Arrive in Bhuj', 'Pick-up at Bhuj airport or station and check in. Evening at leisure.'],
     ['Bhuj sightseeing', 'Aina Mahal, Prag Mahal, the Kutch Museum and a visit to a nearby craft village.'],
     ['Bhuj to Dhordo', 'Drive to the Rann (about 2 hours), visit Kalo Dungar for the view and watch sunset on the white salt desert. Overnight at the tent city.'],
     ['White Rann sunrise and return', 'See the Rann at sunrise, visit Banni artisan villages and return to Bhuj.'],
     ['Departure', 'Transfer to Bhuj airport or station.']]),
  P('udaipur-jaisalmer-lakes-dunes-7d', 'heritage', 'Lakes & Dunes: Udaipur, Jodhpur & Jaisalmer', 6, ['udaipur', 'jaisalmer'], 'Udaipur 2N · Jodhpur 1N · Jaisalmer 2N · Sam dunes camp 1N',
    'A lake-palace city, a blue city and a night in the desert.',
    'From Udaipur’s lakes to Jodhpur’s mighty fort and Jaisalmer’s golden walls, finishing with a night at a desert camp near the Sam sand dunes.',
    ['City Palace, Udaipur', 'Mehrangarh Fort, Jodhpur', 'Jaisalmer Fort', 'Sam dunes camel safari and desert camp'],
    [['Arrive in Udaipur', 'Pick-up and check-in. Evening at Fateh Sagar or Saheliyon Ki Bari.'],
     ['Udaipur sightseeing', 'City Palace, Jagdish Temple and a sunset boat ride on Lake Pichola.'],
     ['Udaipur to Jodhpur via Ranakpur', 'Visit the Jain temples of Ranakpur and continue to Jodhpur (about 6 to 7 hours in total).'],
     ['Jodhpur to Jaisalmer', 'Mehrangarh Fort and Jaswant Thada in the morning, then drive to Jaisalmer (about 5 hours).'],
     ['Jaisalmer and the dunes', 'Jaisalmer Fort and Patwon Ki Haveli, then a camel safari at Sam dunes with folk music and an overnight stay in a desert camp.'],
     ['Dunes sunrise and Jaisalmer', 'Sunrise on the dunes, return to Jaisalmer and visit Gadisar Lake.'],
     ['Departure', 'Transfer to Jaisalmer airport or railway station.']])
];
packages.forEach((p, i) => (p.order = i));

/* ---------- FAQs ---------- */
const faqs = [
  ['How do I book a trip with Skyland Tours & Travels?', 'Send an enquiry through the website or message us on WhatsApp with your destination, dates and number of travellers. We reply with a day-wise itinerary and a quotation, and your booking is confirmed once the advance is received.'],
  ['Can I customise a package?', 'Yes. Every package on this site is a starting point. We can change hotels, add or remove destinations, adjust the pace or build a trip from scratch around your dates and budget.'],
  ['Are flights and train tickets included?', 'Packages cover your stay, local transport and sightseeing as listed in the inclusions. Flights and train tickets are not included unless a package says so, but we can arrange them for you on request.'],
  ['What is the best time to visit India?', 'It depends on the region. North and central India are best from October to March, the Himalayas from March to June and September to October, Ladakh from June to September, and the south and the islands from October to March or May. See our Best Time to Visit guide for details.'],
  ['Do I need a permit for any of the destinations?', 'Some areas need permits, such as parts of Ladakh, Sikkim and the North-East. Permit rules depend on the destination and your nationality and can change, so we confirm the current requirements and arrange permits wherever possible.'],
  ['Which ID do I need to carry?', 'Every traveller should carry an original government photo ID, such as an Aadhaar card, passport, voter ID or driving licence. Foreign nationals need their passport and a valid visa.'],
  ['Do you arrange group tours and corporate travel?', 'Yes. We plan family reunions, friends’ groups, school and college trips, pilgrimage groups and corporate offsites. Tell us the group size and dates and we will suggest the right itinerary and transport.'],
  ['Is it safe to travel with children or senior citizens?', 'Yes, with the right planning. We choose comfortable driving distances, suitable hotels and rest days, and we avoid high-altitude or strenuous activities when they are not suitable. Tell us about any health needs when you enquire.'],
  ['What if the weather or road conditions change my plan?', 'In hill regions, landslides, snowfall or road closures can change plans. Your trip coordinator will rearrange sightseeing wherever possible and keep you informed. Extra costs caused by such disruptions are payable by the guest.'],
  ['How do I pay and what is the refund policy?', 'Payment details are shared with your quotation. Cancellation charges depend on how close to departure you cancel and on non-refundable amounts already paid to hotels and airlines. Please read our Terms & Cancellation page.']
].map(([q, a], i) => ({ id: 'f' + i, q, a, order: i, active: true }));

/* ---------- journal ---------- */
const posts = [
  { id: 'p1', slug: 'best-time-to-visit-india-region-by-region', title: 'Best time to visit India, region by region', date: '2026-09-20', published: true, image: img('destinations/rajasthan.jpg'),
    excerpt: 'India has no single best season. Here is when each region is at its best.',
    body: '<p>India’s size means one region’s peak season can be another’s monsoon. Use this as a quick guide when choosing your dates.</p><h3>North India and Rajasthan: October to March</h3><p>Days are pleasant and nights are cool. Delhi, Agra, Jaipur, Udaipur and Jaisalmer are all at their best, and desert camps are comfortable.</p><h3>The Himalayas</h3><p>Himachal and Uttarakhand work well from March to June and again in September and October. Ladakh is best from June to September, when the high passes are open. Kashmir is lovely from April to October, and Gulmarg is a ski destination in winter.</p><h3>Kerala, Goa and the islands</h3><p>Kerala and Goa are best from October to March. The Andamans are best from October to May.</p><h3>The North-East</h3><p>Sikkim and Darjeeling shine in spring and autumn. Meghalaya is open from October to May, while June to September brings its dramatic waterfalls and heavy rain.</p><p>Not sure which month suits your plans? <a href="/contact">Ask our team</a> and we will suggest dates.</p>' },
  { id: 'p2', slug: 'planning-ladakh-altitude-and-acclimatisation', title: 'Planning Ladakh: altitude and acclimatisation', date: '2026-09-27', published: true, image: img('destinations/ladakh.jpg'),
    excerpt: 'Leh is at about 3,500 metres. Build rest days in and you will enjoy it far more.',
    body: '<p>Leh sits at around 3,500 metres, and Pangong Tso is higher still, at over 4,200 metres. The thin air catches many first-time visitors off guard, so a good Ladakh plan starts with rest.</p><h3>Practical tips</h3><ul><li>Rest on your first day and keep your first two days light.</li><li>Drink plenty of water and avoid alcohol and heavy meals early on.</li><li>Climb gradually: the order of your trip matters, so we plan Leh first, then Nubra and Pangong.</li><li>Carry warm layers, sun protection and any regular medicines.</li><li>Tell your trip coordinator about heart, lung or blood-pressure conditions before booking.</li></ul><p>If you develop a severe headache, breathlessness or confusion, descend and seek medical help. Our Ladakh itineraries include rest days for exactly this reason.</p>' },
  { id: 'p3', slug: 'kerala-houseboat-what-to-expect', title: 'A night on a Kerala houseboat: what to expect', date: '2026-10-02', published: true, image: img('destinations/kerala.jpg'),
    excerpt: 'Meals, timings and tips for your first backwater cruise.',
    body: '<p>A houseboat stay in Alleppey is a highlight of any Kerala trip. Most cruises start around noon and finish by 9 or 10 the next morning.</p><h3>What is on board</h3><p>A houseboat has a private bedroom, a living area and a crew that cooks fresh Kerala meals, usually with fish, rice and vegetable curries. Tell us in advance if you are vegetarian.</p><h3>Tips</h3><ul><li>Boats usually moor for the night by sunset, since cruising in the dark is not permitted on many routes.</li><li>Air-conditioning typically runs only at night, so pack light cotton clothes for the day.</li><li>Carry insect repellent for the evening hours.</li></ul><p>Browse our <a href="/package/kerala-backwaters-7d">Kerala Backwaters & Hills</a> and <a href="/package/munnar-alleppey-honeymoon-6d">Kerala Honeymoon</a> packages to see how a houseboat night fits into a full trip.</p>' }
];

/* ---------- information pages ---------- */
const pages = [
  { slug: 'about-us', title: 'About Skyland Tours & Travels', html: '<p>Skyland Tours & Travels plans holidays, pilgrimages and adventure trips across India, from the Himalayas to the southern tip and from the Thar desert to the Andaman Islands.</p><p>We are a single team for the whole journey: we choose hotels, arrange vehicles and guides, advise on permits and the best season, and stay on call while you travel. Every itinerary on this site is a starting point that we adapt to your dates, budget, group and pace.</p><h3>What we do</h3><ul><li>Holiday packages for families, couples, friends and senior travellers</li><li>Honeymoon and anniversary trips</li><li>Pilgrimage and spiritual tours</li><li>Adventure trips such as Ladakh, rafting and trekking</li><li>Group, school and corporate travel</li><li>Hotels, flights, train tickets, cabs and permit assistance</li></ul><h3>How we work</h3><ul><li>Clear itineraries and pricing before you pay</li><li>Honest advice on the best time to go and what to expect</li><li>A trip coordinator reachable by phone and WhatsApp during your journey</li></ul>' },
  { slug: 'travel-permits-and-documents', title: 'Permits and documents for travelling in India', html: '<p>Most destinations in India need nothing more than a valid photo ID. A few regions have extra rules, and these can change, so we confirm the latest requirements and arrange permits for you wherever possible.</p><h3>Documents every traveller needs</h3><ul><li>An original government photo ID: Aadhaar, passport, voter ID or driving licence</li><li>For children, a birth certificate or school ID</li><li>For foreign nationals, a passport with a valid Indian visa</li></ul><h3>Regions that may need permits</h3><ul><li><b>Ladakh:</b> some areas such as Nubra and Pangong have permit or registration requirements.</li><li><b>Sikkim:</b> places close to the border, such as Nathula, need permits and have limited access days.</li><li><b>North-East states:</b> some states, including Arunachal Pradesh, Mizoram and Nagaland, require an Inner Line Permit or similar approval.</li></ul><p>Rules depend on your nationality and the season. Share your plan and we will tell you what applies.</p>' },
  { slug: 'terms', title: 'Terms & Cancellation Policy', html: '<p><i>These are starter terms. Please review them before relying on them.</i></p><h3>Booking and payment</h3><p>A booking is confirmed once the advance amount is received and acknowledged in writing. The balance is payable before departure, on the date shared with your quotation.</p><h3>Cancellation and refunds</h3><p>Cancellation charges depend on how close to departure the booking is cancelled and on non-refundable amounts already paid to hotels, airlines, railways and other suppliers. The applicable schedule is shared with every quotation.</p><h3>Itinerary changes</h3><p>Sightseeing may be re-ordered or changed because of weather, road conditions, local events or government orders. Extra costs arising from natural calamities, landslides, road closures or strikes are borne by the guest.</p><h3>Travel documents and insurance</h3><p>Guests must carry valid identity documents. We recommend travel insurance for every trip.</p>' },
  { slug: 'privacy', title: 'Privacy Policy', html: '<p><i>Starter policy. Please review before launch.</i></p><p>We collect the details you submit in enquiry forms (name, phone, email and travel plans) only to respond to you, prepare quotations and arrange your trip. We do not sell your data. We may share necessary details with hotels, transport providers and permit authorities to arrange your journey. To ask us to delete your data, contact us using the details on the Contact page.</p>' }
].map(p => ({ id: 'pg-' + p.slug, published: true, ...p }));

module.exports = function seed() {
  return {
    version: 3,
    settings: {
      brand: 'Skyland Tours & Travels', tagline: 'Journeys across India, planned around you',
      heroTitle: 'Discover India, one journey at a time',
      heroSub: 'Holidays, pilgrimages and adventures across every corner of India, planned around your dates, budget and pace by one team that looks after everything.',
      whatsapp: '', phone: '', emails: [], address: '', hours: '', siteUrl: '',
      logo: '/img/logo.svg', favicon: '/img/logo.svg', ogImage: '/img/og.jpg', heroImage: '/img/hero.jpg',
      gstPct: 5, gstIncluded: false, showPrices: true,
      advanceInfo: 'A booking advance confirms your trip. The balance is due before departure.',
      documents: ['Original government photo ID for every traveller (Aadhaar, passport, voter ID or driving licence)', 'Passport and valid Indian visa for foreign nationals', 'Birth certificate or school ID for children', 'Any permit documents we ask for, shared at booking confirmation'],
      payment: { upiId: '', accountName: '', bank: '', accountNo: '', ifsc: '', note: '' },
      announcement: { enabled: false, text: '' },
      social: { instagram: '', facebook: '', youtube: '', linkedin: '', x: '' },
      seo: { title: 'Skyland Tours & Travels | India Tour Packages, Holidays and Pilgrimages', description: 'Pan-India tour packages for Kerala, Rajasthan, Kashmir, Ladakh, Goa, the Himalayas and more. Hotels, transport, permits and trip support by one team.' }
    },
    destinations, packages, departures: [], faqs, testimonials: [], posts, pages, enquiries: []
  };
};
